name: NodeJS

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14, 16, 18 ]
        os: ['ubuntu-latest', 'ubuntu-20.04', 'ubuntu-18.04']

    steps:
    - uses: actions/checkout@v3
    - name: Build NodeJS:${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
