name: React build & upload artifact

on:
  push:
    branches:
      - front-end
      - 'front-end/**'
  pull_request:
    branches:
      - front-end
      - 'front-end/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'windows-latest' ]
        node_version: [ '16', '18' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Application build
        working-directory: frontend
        run: npm run build

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  download_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Download the Artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: build
    
      - name: Message
        run: |
            echo "Artifact downloaded proceeding to upload the image on docker hub" >> $GITHUB_STEP_SUMMARY

  docker:
      needs: download_artifact
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Build
      - uses: docker/setup-buildx-action@v3.0.0
        
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.USER_DOCKER_HUB }}/${{ github.repository }}:${{ github.ref_name }}
