name: React build & upload artifact

on:
  push:
    branches:
      - front-end
      - 'front-end/**'
  pull_request:
    branches:
      - front-end
      - 'front-end/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'windows-latest' ]
        node_version: [ '16', '18' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Application build
        working-directory: frontend
        run: npm run build

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  docker:
    needs: build
    uses: ./.github/workflows/ReactDocker.yml
    secrets: inherit
