name: React build & upload artifact

on:
  push:
    branches:
      - front-end
  pull_request:
    branches:
      - front-end

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-20.04', 'windows-latest' ]
        node_version: [ '16', '18' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.os }}

      - name: Install dependencies
        run: npm install

      - name: Application build
        run: npm run build

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
